Post http://localhost:3000/expenses
Content-Type: application/json

{
  "groupId": "1",
  "title": "Nan",
  "expense": 1000,
  "expenseManagerId": "1"
}

###
GET http://localhost:3000/users/3/expenses

###
GET http://localhost:3000/users/2/debts

###
GET http://localhost:3000/groups/3/settlement